"""Build yt-dlp cookie options; export cookies when the browser DB is locked."""

from __future__ import annotations

import logging
from http.cookiejar import CookieJar
from pathlib import Path
from typing import Any

from app.config import CHROMIUM_BROWSERS
from app.paths import ROOT

log = logging.getLogger(__name__)

COOKIE_CACHE_DIR = ROOT / ".webview"

_COOKIE_COPY_HELP = (
    "Could not read browser cookies.\n\n"
    "Try one of these:\n"
    "- Click 'Sign in to YouTube' (launches your browser with the unlock flag on Chrome/Edge).\n"
    "- Close every window of that browser (check Task Manager), then retry.\n"
    "- Switch to Firefox in cookie settings.\n"
    "- Use 'Cookies file' with an exported cookies.txt\n"
    "  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies\n"
    "Details: https://github.com/yt-dlp/yt-dlp/issues/7271"
)


class CookieExportError(Exception):
    """Raised when browser cookies cannot be exported."""


def cookie_copy_help() -> str:
    return _COOKIE_COPY_HELP


def is_cookie_copy_error(message: str) -> bool:
    lower = message.lower()
    return "could not copy" in lower and "cookie" in lower


def _write_netscape_cookie_file(jar: CookieJar, path: Path) -> bool:
    lines = ["# Netscape HTTP Cookie File", "# Generated by video-downloader", ""]
    count = 0
    for cookie in jar:
        if not cookie.value:
            continue
        domain = cookie.domain or ""
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path_str = cookie.path or "/"
        secure = "TRUE" if cookie.secure else "FALSE"
        expires = str(int(cookie.expires or 0))
        lines.append(
            f"{domain}\t{include_sub}\t{path_str}\t{secure}\t{expires}\t{cookie.name}\t{cookie.value}"
        )
        count += 1
    if count == 0:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return True


def export_browser_cookies(browser: str) -> Path | None:
    """Export YouTube cookies via browser-cookie3."""
    try:
        import browser_cookie3 as bc3
    except ImportError:
        log.debug("browser-cookie3 not installed")
        return None

    loader = getattr(bc3, browser, None)
    if loader is None:
        return None

    jar = None
    for domain in (".youtube.com", "youtube.com"):
        try:
            jar = loader(domain_name=domain)
            if jar and len(list(jar)) > 0:
                break
        except Exception as exc:
            log.debug("browser_cookie3 %s %s: %s", browser, domain, exc)
            jar = None

    if jar is None:
        return None

    path = COOKIE_CACHE_DIR / f"cookies-{browser}.txt"
    if not _write_netscape_cookie_file(jar, path):
        return None
    return path


def ytdlp_cookie_opts(settings: dict[str, Any]) -> dict[str, Any]:
    """Return yt-dlp opts using an exported cookie file (never copy locked Chromium DBs)."""
    cookie_file = (settings.get("cookies_file") or "").strip()
    if cookie_file and Path(cookie_file).is_file():
        return {"cookiefile": cookie_file}

    if not settings.get("use_browser_cookies") or not settings.get("cookies_browser"):
        return {}

    browser = settings["cookies_browser"]
    exported = export_browser_cookies(browser)
    if exported:
        return {"cookiefile": str(exported)}

    if browser in CHROMIUM_BROWSERS:
        raise CookieExportError(cookie_copy_help())

    # Firefox: yt-dlp can read directly when export fails
    return {"cookiesfrombrowser": (browser,)}
